# -*- coding: utf-8 -*-
"""Corelationmatrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZv-YiJZiu9eSaF87OSZffF06Qxd6eev
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing

data = fetch_california_housing()

df = pd.DataFrame(data.data, columns=data.feature_names)
df['Target'] = data.target

print("\nBasic Information about Dataset:")
print(df.info())
print("\nFirst Five Rows of Dataset:")
print(df.head())

print("\nMissing Values in Each Column:")
 print(df.isnull().sum())

plt.figure(figsize=(12, 8))
df.hist(figsize=(12, 8), bins=30, edgecolor='black')
plt.suptitle("Feature Distributions", fontsize=16)
plt.show()

plt.figure(figsize=(12, 6))
 sns.boxplot(data=df)
 plt.xticks(rotation=45)
 plt.title("Boxplots of Features to Identify Outliers")
 plt.show()

plt.figure(figsize=(10, 6))
 corr_matrix = df.corr()
 sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
 plt.title("Feature Correlation Heatmap")
 plt.show()

sns.pairplot(df[['MedInc', 'HouseAge', 'AveRooms', 'Target']], diag_kind='kde')
plt.show()
print("The dataset has", df.shape[0], "rows and", df.shape[1], "columns.")

